name: Deployment Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'


      - name: Install dependencies
        run: |
          npm install
          npm install ts-node jest-environment-jsdom eslint --save-dev
     

      - name: Lint code
        run: |
          npx eslint . --ext .js,.ts --fix
        

      - name: Run tests
        run: npm run test --if-present


  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
         path: ./dist

      - name: Verify build directory
        run: ls -la ./dist || echo "Build directory not found"

      - name: List uploaded artifacts
        run: echo "Uploaded artifacts:" && ls -la ./dist

      - name: Verify build output in dist folder
        run: |
          echo "Checking contents of the dist folder:"
          if [ -d "./dist" ]; then
            echo "dist folder found:"
            ls -la ./dist
          else
            echo "Error: dist folder NOT found. Build might have failed."
            exit 1
          fi


  deployment:
    name: Deploy to GitHub Pages
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: buildArtifact

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
