name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: |
          npm install
          npm install ts-node jest-environment-jsdom eslint --save-dev
        working-directory: ./WebEngineering_BaseTemplate_Jaiczay_Vite_Project

      - name: Lint code
        run: |
          npx eslint . --ext .js,.ts --fix
        working-directory: ./WebEngineering_BaseTemplate_Jaiczay_Vite_Project

      - name: Run tests
        run: npm run test --if-present
        working-directory: ./WebEngineering_BaseTemplate_Jaiczay_Vite_Project

  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./WebEngineering_BaseTemplate_Jaiczay_Vite_Project

      - name: Build project
        run: npm run build
        working-directory: ./WebEngineering_BaseTemplate_Jaiczay_Vite_Project

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./WebEngineering_BaseTemplate_Jaiczay_Vite_Project/dist # Adjust the path to your build output

  deployment:
    name: Deploy to GitHub Pages
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact # Ensure this matches the name used in the upload step

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
