name: Deployment Workflow

on:
  push:
    branches:
      - main

jobs:
  test:
    # Reuse existing workflow
    uses: ./.github/workflows/development.yml

  build:
    runs-on: ubuntu-latest
    needs: test  # This job depends on the completion of the test job
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'

      - name: Install dependencies
        run: npm install
        working-directory: ./WebEngineering_BaseTemplate_Jaiczay_Vite_Project

      - name: Build the project
        run: npm run build
        working-directory: ./WebEngineering_BaseTemplate_Jaiczay_Vite_Project

      - name: Upload build artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: ./WebEngineering_BaseTemplate_Jaiczay_Vite_Project/dist  

  deployment:
    runs-on: ubuntu-latest
    needs: [test, build]  # This job runs after both test and build jobs complete
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup GitHub Pages
        uses: actions/configure-pages@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: build-artifact  # Ensure the name matches what you uploaded

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
