name: Deployment Workflow

on:
  push:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:
  test:
    name: Test Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: |
          npm install
          npm install ts-node jest-environment-jsdom eslint --save-dev

      - name: Lint code
        run: |
          npx eslint . --ext .js,.ts --fix

      - name: Run tests
        run: npm run test --if-present

  build:
    name: Build Application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: ./dist

      - name: Verify build directory
        run: ls -la ./dist || echo "Build directory not found"

      - name: List uploaded artifacts
        run: echo "Uploaded artifacts:" && ls -la ./dist

  deployment:
    name: Deploy to GitHub Pages
    needs: [test, build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v3

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: github-pages

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v2
